### ISSUE TITLE
page view is not returning,,,while returning only simple value

### ISSUE THREAD

**Issue by developer11111** [stackdevelopers/make-admin-panel-in-laravel-5.6#1]
I am having a problem using Laravel Framework. I am trying to build a layout, but no mater how much I've tried I am getting the same error on my browser :

View [layouts.adminLayout.admin_design] not found. (View: 
E:\xampp\htdocs\laravel\ecom2\resources\views\admin\dashboard.blade.php)
m following this tutorial

     https://www.youtube.com/watch?v=bzYBu0iez3s
here is code of admin_design.blade.php

  @include('layouts.adminLayout.admin_header')
  @include('layouts.adminLayout.admin_sidebar')   
  @yield('content')
  @include('layouts.adminLayout.admin_footer')
and this is in dashboard.blade.php

  @extends('layouts.adminLayout.admin_design')
  @section('content')
this is the code of its controller

public function dashboard(){

return view('admin.dashboard');
}   
if i write echo "test"; die;

then it shows die but is not showing the desired page... is there any solution for this prblm

**Comment by stackdevelopers** [comment]
Issue clearly tells that you forgot to add admin_design.blade.php file at path /resources/views/layouts/adminLayout
Once you will add, this issue won't come for sure.
